name: test

on: [push, pull_request]

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 2.5

  test:
    needs: ruby-versions
    name: test (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        git config --global advice.detachedHead 0
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run test
      run: bundle exec rake test
    - id: build
      run: |
        rake build
        echo "pkg=${GITHUB_REPOSITORY#*/}-${RUNNING_OS%-*}" >> $GITHUB_OUTPUT
      env:
        RUNNING_OS: ${{matrix.os}}
      if: >-
        ${{
        github.event_name == 'push' &&
        matrix.ruby == needs.ruby-versions.outputs.latest
        }}
      shell: bash
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        path: pkg/*.gem
        name: ${{steps.build.outputs.pkg}}
      if: steps.build.outputs.pkg
